pipeline {
    agent 
    tools {
        ansible 'ansible'  // Referencing the Ansible installation configured in Global Tool Configuration
    }
    parameters{


        string(name: 'version', defaultValue:'1.1.1', description: 'Who should I say hello to?')
    }
    stages {



        stage('checkout scm') {
            steps {

                sh '''
                 pwd 
                 ls-lart
                 '''
            }
            }

        

        stage('Run Ansible Playbook') {
            steps {

                 withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_KEY')
                ])
                {
                    sh '''
                    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
                    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
                   
                    '''
                }
                script {
                    ansiblePlaybook(
                        playbook: 'deploy.yml',
                        inventory: 'aws-ec2.yml',
                        additionalOptions: "--extra-vars \"nginx_version="${params.version}\""
                    )
                }
            }
        }
    }
}

